const cities = [
      { id: 1, name: "Chennai" },
      { id: 2, name: "Coimbatore" },
      { id: 3, name: "Madurai" },
      { id: 4, name: "Tiruchirappalli" },
      { id: 5, name: "Salem" },
      { id: 6, name: "Erode" },
      { id: 7, name: "Tirunelveli" },
      { id: 8, name: "Vellore" },
      { id: 9, name: "Thoothukudi" },
      { id: 10, name: "Nagercoil" },
      { id: 11, name: "Thanjavur" },
      { id: 12, name: "Dindigul" },
      { id: 13, name: "Karur" },
      { id: 14, name: "Kumbakonam" },
      { id: 15, name: "Mannargudi" },
      { id: 16, name: "Cuddalore" },
      { id: 17, name: "Tiruppur" },
      { id: 18, name: "Namakkal" },
      { id: 19, name: "Thiruvananthapuram" },
      { id: 20, name: "Kochi" },
      { id: 21, name: "Kozhikode" },
      { id: 22, name: "Thrissur" },
      { id: 23, name: "Kollam" },
      { id: 24, name: "Palakkad" },
      { id: 25, name: "Alappuzha" },
      { id: 26, name: "Kannur" },
      { id: 27, name: "Kottayam" },
      { id: 28, name: "Malappuram" },
      { id: 29, name: "Pathanamthitta" },
      { id: 30, name: "Idukki" },
      { id: 31, name: "Wayanad" },
      { id: 32, name: "Kasargod" }
    ]
  
    export default cities